version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: hackaton-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackaton
      MYSQL_USER: hackaton
      MYSQL_PASSWORD: hackaton
    ports:
      - "3306:3306"
    volumes:
      - ./BaseDeDatosHackaton.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: hackaton-backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: hackaton
      DB_PASSWORD: hackaton
      DB_NAME: hackaton
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: hackaton-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
